// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: marketstat.sql

package priceLogger

import (
	"context"
)

const addPrice = `-- name: AddPrice :exec
INSERT INTO public.wsminimarketsstatevent ("event","time",symbol,last_price,open_price,high_price,low_price,base_volume,quote_volume)
	VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type AddPriceParams struct {
	Event       string `json:"event"`
	Time        int64  `json:"time"`
	Symbol      string `json:"symbol"`
	LastPrice   string `json:"last_price"`
	OpenPrice   string `json:"open_price"`
	HighPrice   string `json:"high_price"`
	LowPrice    string `json:"low_price"`
	BaseVolume  string `json:"base_volume"`
	QuoteVolume string `json:"quote_volume"`
}

func (q *Queries) AddPrice(ctx context.Context, arg AddPriceParams) error {
	_, err := q.db.ExecContext(ctx, addPrice,
		arg.Event,
		arg.Time,
		arg.Symbol,
		arg.LastPrice,
		arg.OpenPrice,
		arg.HighPrice,
		arg.LowPrice,
		arg.BaseVolume,
		arg.QuoteVolume,
	)
	return err
}
