// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package priceLogger

import ()

type Wsminimarketsstatevent struct {
	ID          int64  `json:"id"`
	Event       string `json:"event"`
	Time        int64  `json:"time"`
	Symbol      string `json:"symbol"`
	LastPrice   string `json:"last_price"`
	OpenPrice   string `json:"open_price"`
	HighPrice   string `json:"high_price"`
	LowPrice    string `json:"low_price"`
	BaseVolume  string `json:"base_volume"`
	QuoteVolume string `json:"quote_volume"`
}
